import streamlit as st
import time

with st.spinner('Wait for it...'):
    time.sleep(1)

st.markdown(
    """
    <style>
    .title {
        text-align: center;
    }
    </style>
    """, unsafe_allow_html=True
)

# Title that will be centered
st.markdown('<h1 class="title">My Internships</h1>', unsafe_allow_html=True)
st.subheader("", divider=True)

st.markdown('<h2 class="title">Inorbvict Healthcare India Pvt Ltd</h2>', unsafe_allow_html=True)
col1, col2, col3, col4 = st.columns([1,2,4,1], gap="small", vertical_alignment="center")
with col1:
    st.write( )

with col2:
    # Example image path
    # img_path = "./assets/test.png"

    # # HTML to center the image
    # html = f'<div style="text-align: center;"><img src="{img_path}" width="300"/></div>'

    # # Display the centered image
    # st.markdown(html, unsafe_allow_html=True)
    st.image("./assets/test.png", width=300)
    st.markdown(
        """
        <a href="https://www.google.com" target="_blank">
            <button style="
                background-color: #586e75; 
                color: white; 
                padding: 10px 20px; 
                border: none; 
                cursor: pointer; 
                font-size: 16px;
                border-radius: 12px;  /* Rounded corners */
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); /* Shadow effect */
                transition: background-color 0.3s ease, transform 0.3s ease; /* Smooth transition */
            ">
                <b>Certificate</b>
            </button>
        </a>
        <style>
            button:hover {
                background-color: #45a049; /* Darker shade on hover */
                transform: scale(1.05); /* Slightly enlarge on hover */
            }
        </style>
        """, unsafe_allow_html=True
    )

with col3:
    st.markdown(
    """
        <style>
        .align-right {
            text-align: left;
        }
        </style>
        """, unsafe_allow_html=True
    )

    # Display text with right alignment using custom class
    st.markdown('<p class="align-right"><I><B>Sep 2024 - Jan 2025</B></I></p>', unsafe_allow_html=True)
    st.markdown('<p class="align-right"><I><B>HTML | CSS | JS | Bootstrap | PHP | SQL | AJAX | jQuery.</B></I></p>', unsafe_allow_html=True)
    st.write("""
             - Built a web application for a Gram Panchayat that improved citizen service delivery by 20% with a user-friendly interface
(HTML, CSS, JavaScript, Bootstrap). The application allows citizens to easily access and apply for various services offered
by the Panchayat, eliminating the need for physical visits and long wait times.
- Enhanced data accessibility for Panchayat officials using real-time dashboards and reports generated by the web
application (SQL, PHP, Ajax). This empowers officials to track application progress, identify resource needs, and make
data-driven decisions for improved service delivery within the Gram Panchayat.
             """)
with col4:
    st.write( )





st.subheader("", divider=True)

st.markdown('<h2 class="title">Inorbvict Healthcare India Pvt Ltd</h2>', unsafe_allow_html=True)
col1, col2, col3, col4 = st.columns([1,4,2,1], gap="small", vertical_alignment="center")
with col1:
    st.write( )


with col2:
    st.markdown(
    """
        <style>
        .align-right {
            text-align: left;
        }
        </style>
        """, unsafe_allow_html=True
    )

    # Display text with right alignment using custom class
    st.markdown('<p class="align-right"><I><B>Sep 2024 - Jan 2025</B></I></p>', unsafe_allow_html=True)
    st.markdown('<p class="align-right"><I><B>HTML | CSS | JS | Bootstrap | PHP | SQL | AJAX | jQuery.</B></I></p>', unsafe_allow_html=True)
    st.write("""
             - Built a web application for a Gram Panchayat that improved citizen service delivery by 20% with a user-friendly interface
            (HTML, CSS, JavaScript, Bootstrap). The application allows citizens to easily access and apply for various services offered
            by the Panchayat, eliminating the need for physical visits and long wait times.
            - Enhanced data accessibility for Panchayat officials using real-time dashboards and reports generated by the web
            application (SQL, PHP, Ajax). This empowers officials to track application progress, identify resource needs, and make
            data-driven decisions for improved service delivery within the Gram Panchayat.
             """)

    # Design a button with border radius, hover effect, and custom styling
    
with col3:

    st.image("./assets/test.png", width=300)
    st.markdown(
        """
        <a href="https://www.google.com" target="_blank">
            <button style="
                background-color: #586e75; 
                color: white; 
                padding: 10px 20px; 
                border: none; 
                cursor: pointer; 
                font-size: 16px;
                border-radius: 12px;  /* Rounded corners */
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); /* Shadow effect */
                transition: background-color 0.3s ease, transform 0.3s ease; /* Smooth transition */
            ">
                <b>Certificate</b>
            </button>
        </a>
        <style>
            button:hover {
                background-color: #45a049; /* Darker shade on hover */
                transform: scale(1.05); /* Slightly enlarge on hover */
            }
        </style>
        """, unsafe_allow_html=True
    )


with col4:
    st.write( )




st.subheader("", divider=True)

st.markdown('<h2 class="title">Inorbvict Healthcare India Pvt Ltd</h2>', unsafe_allow_html=True)
col1, col2, col3, col4 = st.columns([1,2,4,1], gap="small", vertical_alignment="center")
with col1:
    st.write( )

with col2:
    st.image("./assets/test.png", width=300)
    st.markdown(
        """
        <a href="https://www.google.com" target="_blank">
            <button style="
                background-color: #586e75; 
                color: white; 
                padding: 10px 20px; 
                border: none; 
                cursor: pointer; 
                font-size: 16px;
                border-radius: 12px;  /* Rounded corners */
                box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); /* Shadow effect */
                transition: background-color 0.3s ease, transform 0.3s ease; /* Smooth transition */
            ">
                <b>Certificate</b>
            </button>
        </a>
        <style>
            button:hover {
                background-color: #45a049; /* Darker shade on hover */
                transform: scale(1.05); /* Slightly enlarge on hover */
            }
        </style>
        """, unsafe_allow_html=True
    )

with col3:
    st.markdown(
    """
        <style>
        .align-right {
            text-align: left;
        }
        </style>
        """, unsafe_allow_html=True
    )

    # Display text with right alignment using custom class
    st.markdown('<p class="align-right"><I><B>Sep 2024 - Jan 2025</B></I></p>', unsafe_allow_html=True)
    st.markdown('<p class="align-right"><I><B>HTML | CSS | JS | Bootstrap | PHP | SQL | AJAX | jQuery.</B></I></p>', unsafe_allow_html=True)
    st.write("""
             - Built a web application for a Gram Panchayat that improved citizen service delivery by 20% with a user-friendly interface
(HTML, CSS, JavaScript, Bootstrap). The application allows citizens to easily access and apply for various services offered
by the Panchayat, eliminating the need for physical visits and long wait times.
- Enhanced data accessibility for Panchayat officials using real-time dashboards and reports generated by the web
application (SQL, PHP, Ajax). This empowers officials to track application progress, identify resource needs, and make
data-driven decisions for improved service delivery within the Gram Panchayat.
             """)
with col4:
    st.write( )
