import streamlit as st
import time

with st.spinner('Wait for it...'):
    time.sleep(2)


st.markdown(
    """
    <style>
    .title {
        text-align: center;
    }
    </style>
    """, unsafe_allow_html=True
)

# Title that will be centered
st.markdown('<h1 class="title">My Projects</h1>', unsafe_allow_html=True)
st.subheader("", divider=True)

col1, col2, col3, col4 = st.columns([1,4,4,1], gap="medium", vertical_alignment="top")
with col1:
    st.write( )

with col2:
    # Example image path
    # img_path = "./assets/test.png"

    # # HTML to center the image
    # html = f'<div style="text-align: center;"><img src="{img_path}" width="300"/></div>'

    # # Display the centered image
    # st.markdown(html, unsafe_allow_html=True)
    st.image("./assets/test.png", width=300)
    st.markdown('<h2 class="title">Inorbvict Healthcare India Pvt Ltd</h2>', unsafe_allow_html=True)
    st.write("""
             - Built a web application for a Gram Panchayat that improved citizen service delivery by 20% with a user-friendly interface
(HTML, CSS, JavaScript, Bootstrap). The application allows citizens to easily access and apply for various services offered
by the Panchayat, eliminating the need for physical visits and long wait times.
- Enhanced data accessibility for Panchayat offici
             """)
    st.markdown('<p class="align-right"><I><B>HTML | CSS | JS | Bootstrap | PHP | SQL | AJAX | jQuery.</B></I></p>', unsafe_allow_html=True)


with col3:

    st.image("./assets/test.png", width=300)
    st.markdown('<h2 class="title">Inorbvict Healthcare India Pvt Ltd</h2>', unsafe_allow_html=True)
    st.write("""
             - Built a web application for a Gram Panchayat that improved citizen service delivery by 20% with a user-friendly interface
(HTML, CSS, JavaScript, Bootstrap). The application allows citizens to easily access and apply for various services offered
by the Panchayat, eliminating the need for physical visits and long wait times.
- Enhanced data accessibility for Panchayat officials using real-time dashboards and reports generated by the web
application (SQL, PHP, Ajax). This empowers officials to track application progress, identify resource needs, and make
data-driven decisions for improved service delivery within the Gram Panchayat.
             """)    
    st.markdown('<p class="align-right"><I><B>HTML | CSS | JS | Bootstrap | PHP | SQL | AJAX | jQuery.</B></I></p>', unsafe_allow_html=True)

with col4:
    st.write( )

st.subheader("", divider=True)

col1, col2, col3, col4 = st.columns([1,4,4,1], gap="medium", vertical_alignment="center")
with col1:
    st.write( )

with col2:
    # Example image path
    # img_path = "./assets/test.png"

    # # HTML to center the image
    # html = f'<div style="text-align: center;"><img src="{img_path}" width="300"/></div>'

    # # Display the centered image
    # st.markdown(html, unsafe_allow_html=True)
    st.image("./assets/test.png", width=300)
    st.markdown('<h2 class="title">Inorbvict Healthcare India Pvt Ltd</h2>', unsafe_allow_html=True)
    st.write("""
             - Built a web application for a Gram Panchayat that improved citizen service delivery by 20% with a user-friendly interface
(HTML, CSS, JavaScript, Bootstrap). The application allows citizens to easily access and apply for various services offered
by the Panchayat, eliminating the need for physical visits and long wait times.
- Enhanced data accessibility for Panchayat officials using real-time dashboards and reports generated by the web
application (SQL, PHP, Ajax). This empowers officials to track application progress, identify resource needs, and make
data-driven decisions for improved service delivery within the Gram Panchayat.
             """)
    st.markdown('<p class="align-right"><I><B>HTML | CSS | JS | Bootstrap | PHP | SQL | AJAX | jQuery.</B></I></p>', unsafe_allow_html=True)


with col3:

    st.image("./assets/test.png", width=300)
    st.markdown('<h2 class="title">Inorbvict Healthcare India Pvt Ltd</h2>', unsafe_allow_html=True)
    st.write("""
             - Built a web application for a Gram Panchayat that improved citizen service delivery by 20% with a user-friendly interface
(HTML, CSS, JavaScript, Bootstrap). The application allows citizens to easily access and apply for various services offered
by the Panchayat, eliminating the need for physical visits and long wait times.
- Enhanced data accessibility for Panchayat officials using real-time dashboards and reports generated by the web
application (SQL, PHP, Ajax). This empowers officials to track application progress, identify resource needs, and make
data-driven decisions for improved service delivery within the Gram Panchayat.
             """)
    st.markdown('<p class="align-right"><I><B>HTML | CSS | JS | Bootstrap | PHP | SQL | AJAX | jQuery.</B></I></p>', unsafe_allow_html=True)

with col4:
    st.write( )